# All values in no of frames

BACKGROUND_COLOR: lightgray

FRAME_RATE: 60

NO_GO_TRIALS_TRAINING: 10

NO_NO_GO_TRIALS_TRAINING: 10

NO_TRAINING_TRIALS: 20

NO_GO_TRIALS_BLOCK_EXPERIMENT: 25

NO_NO_GO_TRIALS_BLOCK_EXPERIMENT: 25

STIM_DURATION_IN_FRAMES: 90

FRAMES_BETWEEN_STIMS: 27

STIM_SIZE: 500

REACTION_KEY_RIGHT: ['right']

REACTION_KEY_NONE: ['None']

SCREEN_RES: [1440, 900]

NO_BLOCKS_IN_EXPERIMENT: 4

NO_TRIALS_IN_BLOCK: 50

FIX_CROSS_TIME: 48

FIX_CROSS_COLOR: black

Stim_type: ['kolko', 'kwadrat']



